[package]
name = "error-collection"
authors = ["MarcGuiselin"]
categories = ["rust-patterns", "development-tools::debugging"]
version = "1.0.4"
edition = "2024"
description = "A generic collection around dynamic errors"
license = "MIT OR Apache-2.0"
homepage = "https://crates.io/crates/error-collection"
repository = "https://github.com/MarcGuiselin/error-collection"
readme = "README.md"
publish = true

[dependencies]
anyhow = "1.0"
derive_more = { version = "2", default-features = false, features = [
  "deref",
  "deref_mut",
] }
